export let schemes = {}
schemes = {
  Def: {
    backgroundColor: '#146B66',
    lightBackgroundColor: '#AFEFDF',
    questionTextColor: 'black',
    color: 'black',
    buttons: '#AFEFDF',
    buttonsText: 'black',
    viewBackgroundColor: '#146B66',
    placeholderTextColor: 'black',
    linearBackgroundColor: ['#93F5EF', '#146B66', 'black'],
    linearButton: '#AFEFDF',
    linearButtonText: 'black',
    borderColor: 'black',
    shadowColor: '#AFEFDF',
  },

  Dark: {
    backgroundColor: '#1F1B24',
    lightBackgroundColor: '#821EFC',
    questionTextColor: 'black',
    color: '#BB86FC',
    buttons: '#BB86FC',
    buttonsText: 'black',
    viewBackgroundColor: '#121212',
    placeholderTextColor: '#BB86FC',
    linearBackgroundColor: ['#1F1B24', '#1F1B24', '1F1B24'],
    linearButton: '#BB86FC',
    linearButtonText: '#FEFEFE',
    borderColor: 'black',
    shadowColor: '#BB86FC',
  },

  EasyReadColor: {
    backgroundColor: '#515050',
    lightBackgroundColor: 'White',
    color: '#FEFEFE',
    questionTextColor: 'black',
    buttons: '#FEFEFE',
    buttonsText: 'black',
    viewBackgroundColor: '#515050',
    placeholderTextColor: 'white',
    linearBackgroundColor: ['#515050', '#515050', '#515050'],
    linearButton: '#FEFEFE',
    linearButtonText: '#FEFEFE',
    borderColor: 'black',
    shadowColor: '',
  },
}
