export let schemes = {}
schemes = {
  Def: {
    backgroundColor: '#146B66',
    lightBackgroundColor: '#93F5EF',
    color: 'black',
    buttons: '#AFEFDF',
    buttonsText: 'black',
    viewBackgroundColor: '#146B66',
    placeholderTextColor: 'black',
    linearBackgroundColor: ['#93F5EF', '#146B66', 'black'],
    linearButton: '#AFEFDF',
    linearButtonText: 'black',
    borderColor: 'black',
    winnerScreenQuit: 'gray',
    headerColor: '#121212',
    shadowColor: '#FFFFF',
  },

  Dark: {
    backgroundColor: '#121212',
    lightBackgroundColor: '#821EFC',
    color: '#BB86FC',
    buttons: '#BB86FC',
    buttonsText: 'black',
    viewBackgroundColor: '#121212',
    placeholderTextColor: '#BB86FC',
    linearBackgroundColor: ['#821EFC', '#BB86FC', 'black'],
    linearButton: 'black',
    linearButtonText: '#FEFEFE',
    borderColor: '#FFFFFF',
    headerColor: 'green',
    shadowColor: '#FFFFFF',
  },

  EasyReadColor: {
    backgroundColor: '#FFFFFF',
    lightBackgroundColor: '#FFFFFF',
    color: '#FFFFFF',
    buttons: '#515050',
    buttonsText: '#FFFFFF',
    viewBackgroundColor: '#515050',
    placeholderTextColor: '#FFFFFF',
    linearBackgroundColor: ['#93F5EF', '#146B66', 'black'],
    linearButton: 'black',
    linearButtonText: '#FEFEFE',
    borderColor: 'black',
    headerColor: '#121212',
    shadowColor: '',
  },
}
